### ISSUE TITLE
musicbrainz integration just half working

### ISSUE THREAD

**Issue by legacychimera247** [NickvisionApps/Tagger#257]
hello there, very nice tagger has a musicbrainz integration, but unfortunately it's just half working

i'll give you an example:

open tag, select a record and choose to obtain info from musicbrainz, no data is retrieved
open picard, select data with fingerprint (that should be the same as tagger does) and the album is recognized almost instantly

between closing tagger and opening picard i thought the record did not have fingerprint ids so started adding them via tagger, but either this does not work as, per tagger, the fingerprint id sent to musicbrainz is wrong

pratically there's no way to use this feature, unless the album as already been tagged with picard, this seems to be the only way to have this working...

**Comment by legacychimera247** [comment]
don't really know as it seems to work now, need to do further tests

anyway the message displayed was something like "musicbrainz received an invalid id" despite the id being sent by me directly via tagger...

**Comment by legacychimera247** [comment]
ok found another of these situations

the app tagged the entire album except for this single song (crash and carry) so provided the acoustID myself but it's still not working

![image](https://github.com/NickvisionApps/Tagger/assets/22254556/f7fdade6-6a06-4099-a001-c6ed7b7f2182)

**Comment by legacychimera247** [comment]
here it is, for the same exact song...

`AQACMkkoKUmiJFSExkbRUgn842UMO9nR4svQ9YG_o11wC6qJXjv8o6jODyK54j38xeiP6_gA7Ufz4jxyNM5ShO_RmUbDQD_CPER__MGVo6fRPEIeRji0cPnQ8_gVNNXRJ1GO59ASF33Q_QhThST-IPTxEECj6zj-o44Od0fsCelf3LDMB72No88hvujkWDgP9XSKNmgs_ER1oTn-o-lIos8D_ehzfIKPrr3xBz-aOkY1aahHQuSkwupy1KOF_PhQq_CPrhry4-5xtIkPFz5R7cd9NDJJos9R34b44MOPrsd3_GhCx-hRcVEI8UQnH8151Aod3HiEnmhUHP_xo2GOXkO9FU1uHI2Uk-iT46hV-NC-4xr-4x_qEXaPxxA_4s_hH6EVOjjOoRfCSKSP1zHUPzhRU_B5vIJvaHvReDr6ED9eow8O4w0hb_AFRkd_aIlxvAgfUkD6FrWiFId2Bo18VDTMG8cH8ThtWM3ww0cboc9BoZ_RTROc4_jx5dALOJRwLYRwnAqRw8f94zxS4YR_tAMO7cWpfOjxHg0X9BNRj_CPH-5xOF-gyaiNt0TKRcHxqMTxG6nwk4QHE3oulDg0ibBMnMcPM8IdHh6-wz8efMKVHSe-gz-OdD2-I_dhDj26G29w_PAXiDV-wLfQeegJ_fh4-MXxQ_vxBQ9zHNrhNBOHNsPbHD0OPys6_NBk5rjQRtCz4CFuorHRbdLx4-gLn-iPQ7vwZtiFJzuOHTrRUMQ-5BfaI9qzo8cr9MeXQdeh8zhpPDuewcK34wSPHw9ElcJxSwfjHdeIPoN6UB866njE40f1w8-PCm9wSBd-9LChHr6JwzlxHccZnISPrsWnBTfaw6cByzwO9_CPz2jO4cSL5qin5AOuo_lx4xKO-kfXhzAk8xAPHz_6GN8O_ugHPbgOv9C8He-JPvgK_8LRFT2cLfCPT8GPHi-ai-ia4-hJ-EF_CH1hWWj64wuq2iDENGipB9_RH-9xwldwyAcfBf1xBe0Y6D6i5eiL4586FA0l4T3-Ykp8o12QLPoRPju-Cz-ebCua9-g7_LgehP-RXLD04Dx6vEc-ZVygEXwPZ0JPfMvxE5oukNcROyR8HiF20tCDhsoR1gkqCp80HKGBZD_8DJ12_MNunLFwYzrC_FBeGZ2W4Iey6hFiodcVTLkelHh2VMsIfx3KIrGPnDx-4dnRX3h5-PiJHvkP7UQqE9V-5NgvaA8TpPmD69iPUFRY4Q0U_UKaY3p2PK3xoz9S_tB1-MgRj4LVozd0Iz86LYGPvgfCrTl0Epdy5IM_vPhfhJK-4UENcwGgBDEIEAuAAgAoIpAQyhEFGGICEIeAMw4JAaRJAgABgTIIEaEUYAKYgICRSCAAkCCAEYAAQYIIgAgQkhFABTBCKSUMCACYoABAAigAmAUECocAIIAoQ0hAgikAEAkAiSEIE0Y4AQwRQiCikACMECYYUEQIaZgATSKikBCACiIco4AhJYgF5ghEkJBAKYCEE0AYLgBgwghKhGEmCGocIQAggxgABggGBBFQGAIFYU4waYCyyAEqgDECESSEEwQZoABVAmAGKBAOKSAYMkIIZJIQSlgvhUICCEEZMAQhYhRRSDDilLSAICMQQIZ4YAAQgIkgiCJGAYSYs1YIIIRxwjDFHBIGIGKdAgAphBhSQilCjGEACIKMEJYhgIwDwBjEgEACACMEEogJJ5khQiEEgGAKMIEAUUIQYxBTACnGlFACEMEEIgoIIJBhggIBgEBMKCaAgkAwQZAQoBCgAFFAKIGYMUYYBpATwigiADHIAAMEIIghYYQAVAgCBCFWKUYcQsIQZIiBRBghFA`

**Comment by legacychimera247** [comment]
still i remember the one pasted was much much shorter...

**Comment by nlogozzo** [comment]
Ok I'll take a look...thanks!

**Comment by nlogozzo** [comment]
@legacychimera247 ok could you run tagger in the terminal `flatpak run org.nickvision.tagger` and try to download musicbrainz metadata for that `crash and carry` file again and see if any error messages are printed in the terminal

**Comment by Saltane** [comment]
Hello, have had same issue with Tagger since initial install. Whatever track I'm trying to metadata automatically, no track is being succesful. The error is always the same:
<img width="247" alt="зображення" src="https://github.com/NickvisionApps/Tagger/assets/101461606/f9053643-6610-4138-96f7-8bb61e78324d">
Tried renaming file itself, didn't work.
Here's fingerprint for Dear Agony, which you can see on screenshot:

`AQADtFmURYkSJUmDMtMz3Kiqo6lTXFAV4shzON6Hp8cJU5vxU_iR_sLDQ99xIWfQX8h_7FMGOx3R_9CD5kKkHk-NPluCD9FH6BP8Bs64VEhVHf2CWCZ0HT_CbgqaVMfx6UPhR-qCvHCvQm0-_MiV4zzxi3hvXHIO_7iH8DLkCVce5BGu42pQWnCeI1eLUpvxHd8hHmcWXAxuGz1EeWjDI1TD4PLh4ZE-ZNcCtzmuY4fR_9hzXMoCG1cWHTmuRNHwHE9w60F_nDvMB1cP5D8O7ZmFV8dToVYOswczL8WZg8OH9-j9g-rwvfh1rC9UVejxUMiN6wrRSHsQSlKOQ-VxtkOVRjBv9MfxC0-kHVp-VMXf4znR90jlHBcQPdBGoueRpsmDvgXv48txkeh6bH_Rx0VMQg9iJQqeP0HPnGiCL8Z1hBaNJmZ2PAyqQZcybUZILwvO46OEHp_QcDm-Hf8G5wviG4di5kFKXcKb4r3gG5yPPzomMS-aXrhxnXiOnMOn48nRo9mFfyaeWKSgnDLC5hSeGs929Hj2o9ka7qj9BP_xHj6iC7qOPBq-nGh-ofyK_8LNjEcf_OiN8ziPS8LDG0fzLD0qHU8THXkHHbmKUunhH_3xLsdzXC7GnkioSUoRi1Hw9HiOow9fMPmD68iX_dCeFYb6Icefg2F2lDIeKfgXNOuDHJdiKCKJPMmM2viD6rCCidmNH_yKnkf_FNkj6IilJBijo42OZlKW4sWOfkGTNFEETtFxHT2Twt_RC88e7D3eItQVaEnCDIgenEEtkYRHJYG5DFke6PyQ50PThESt_Ph1dEV4_LgYLoh7uFSORw_OMOiN5vjhPMizK8P9QcsoBR-L86jzBLmI-_CD42mOM_pRG_7Cw5M-0MK_ggmXE6eOygumqIky4T_i5kjOLBcavsTX4NJxHJV15MqDpBkVXHh4oSTeBhd_vFmQLEd-XMxi3MNFeFY6HD-8KFPw5niKJjd65rhQC72C_At0lP6RLlSCSSaQQ7N25EVbifhEnEd_NLPIIP6h78gjXAyuZQij_IF2pgriz8KNz8aN85EQ5jnK59DiInwtsHrwJ0T5Isxz_PgPzQwYJdQRPw8uPDv644F5F2WD_NCFfsIlwbuEb3kh7rAbXBKPVBZCCTuD_ugPPXqQKzJKMmiq4Tvx40mULUZOJE1EosncocaZXOgvJMvbIcfHoNSOw_kShNeF5MHnHE8SvCzu_ahtNE1z3Mct8eiXHGHGHMqf4-SHWpEDn-iVQy_xbyhv_Ao6KTv-pbguXEJ7Ir8MpFs6fJDeIctxHZxy_PiUPOB5hIc2H7Hy48WO5jPqREbe42SOV8eR92iexTjJwzp8XAzCUh90orqQXkkT5MvRJ8WlQQsrI7Tz4A-qw_JiOOYR2sbeQ0doHV4Wiyj340dzfEHXZTuOU8H5IA-0x4S7wS9y4zqaRozxc-h5ODlC4o7BPDz8I2Rn0Eel7cWX4hEscSi7TKj8GD4YKycu-ch5Q1fwC7lyBc2ZinjQHNeLK8qP60Eeoech6Tl-8Mgv483xbMeRX-jRf0KOKkPcZBTuEPonhOnANAmPs5iSH91l_KKCHvU85B_y4DzKPUazLPrw4ynCxNKh7QiuB3909IOnCr2OC-1-NHs2XEefoDn-4NWCXidyvDfUankw_chPBAWTQ4-Mp8zAHpcuaEf6Jcd74bqCXCKuvPghFp_xDD1-vDnCnE3QpSWquWjGoxaaBx9-BZGvoF10iCOO8Ily3MHP4THRhEfH4zjRE81V_EdOkniilIP2463gzziPsD_-EGePRjda9cMfozl6PnicCL0OcynKY7-EPjgc9CyNdQ5-hNwD8fCXbOiFu_hGdM_QxPmw58MvhBZz_BzCgw-Pk7gkU7gSRcUfEj8a6pBi5ciP_iya6OAd9EZznDlunDJy1KIDv4JaJvCDPhc-xvgWHVngX_iPH9FzfDpQPlDxHXqM9nEMO_yQM8dT-MRLnMeDr0KvI89GJG5xkbiEkrjhV0Z__MKzHE_0o3qKSFEKdSeQvUb74yx-uGCoKDe-K0EpNGZOnNJmxCaS48KVx6giPjiqE2d19EdznE_xFC_zFLmOyxfa5YP3oJmEa8GXHdoqC012Lsh74z9-vBu4H8_y4tKH5hnRD80lC_0G4uODiNmWQfyFXD-OylrQ6A8eHZWPJnSO_8F15Au0jETtHMcTHvmFa5fRvOhxyehvNA-SJ0cu8bgiHQ-J80VPNN3xhDieiAvKfITH6AgfTKJBNvhRKV7BQhdCO3iEG98DK1WOkgyHPNATIf_hZ2Hw4zk4MxbRZ0YI7ZeQPeRxScZ59N3x8PiZIEx39IfOI09xHpWWrXCyBf1w4Md3FH9y5BIuwRcu5iueG2-GK0GqDqFE7Axu6EeeoI4iwxxzlBK-4_vw8DHyRIF-hEnio1pwDs8phDlzaEf-41GGkjzeIEw-Q9eRrzmuRXiyGf9Ri2ia5sVz4ubRKyPS78JE5oJuHQy1XPAP5sdL6PmG8sYfVKmOX0nxC5fQm_hxeEsH6QrCo39QkvgO9iGu5MGP5JKQG1cAQwwlQAJDGDFOAaOAJYQIpQwQQgBEKFOOEIQkUIopMAQASlDojAEMKQEIIEI4gAA1BBjDiKLEIEQIMEgIJgwhQAOCiEgSKAIYAMoJAQQQwxBqhBLOIACAA0AAI5ABDhHliLPEJKUIQAIYYwQgiAmADACGAgUEM0IAAZAyRgAnjGaMMGSAYYgwApUQDhBFIqFAIIGMAgAAaJRx1gABBABAGMKQAgYoYQQBAACkNCMOIAREAAII6g2gQhECCEOAEEaYAEBxQAAgAAAgkEIGQWacRAwYRJgwDDGkrCBECeEsMgI4AQgIRhkhgCOEC8QYA8wgS4wRSACimGECwYAAIMIIpAABiAEBACAUmWQYUMQABIRAAASKyAiEACOcskooAQAUBDBCCCEEIaGIAIggRAgQhigDBIDIKCSMAdQYACmQxgHMAHLIAIIEEwYhxYxSRCgFhEEUCMGEIEQAIAQBQggEgCIAGKOYEEAwAJgRkRBETGSKCASAEQY4ooURBBiCkABASIQEEEQoZACBThFHFANAACdEIIQAQBECQBCJABFEECcQAgwowpgwBlABnDAACAaAMIyhoQAChAnBlHAIAEMAEAAoJZADTCBBFSQMAGKNAIYIJBUBBAjihgBKGCEUYMAowAhhRBpDmGUkKaAIRo4ZBhBwCAqmDGIECIMEUYAJogAghAgigBFAGEO8UVgL4BQBxgFiiCHCOKSMYMAIAp0CRBAAgRIMIcIUAMYIgQAhgBlDhBSGIkCEoUAB4JgRChimiEIKMQaEIYIwQpUxBgCMiELEMCEFRYYCYAwwBCpghEBIAUWYgcIABATAACCACHECKEGBIAJ4wqBCygAFOGACOGAMMAIAQRBsjCikGCLAEUIkAMBA4QQhSCBngCKMEEIAEiIJghJVggDiuAWCAIUAWcorhBhQQBFBiDNAYEGAAQwgAwggABjBEAAGCCQUAIYZZ4QwwAHAlDhYsMAkAUAgIwkBAA`

Tried running Tagger from terminal, no error messages… not useful ones at least:
<img width="903" alt="зображення" src="https://github.com/NickvisionApps/Tagger/assets/101461606/110103f4-0fa7-475f-8fae-6e9cd73071f7">

**Comment by legacychimera247** [comment]
hello, unfortunately i've tagged the song with picard so it's now working, but this is the report from another song in the same situation

`Not Found (For usage, please see: https://musicbrainz.org/development/mmd)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`1 request, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(String entity, String id, String extra, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync[T](String entity, String id, String extra, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Query.LookupRecordingAsync(Guid mbid, Include inc, Nullable`1 type, Nullable`1 status, CancellationToken cancellationToken)
   at NickvisionTagger.Shared.Models.MusicFile.LoadTagFromMusicBrainzAsync(String acoustIdClientKey, String version, Boolean overwriteTagWithMusicBrainz, Boolean overwriteAlbumArtWithMusicBrainz) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 490`

**Comment by Saltane** [comment]
Hello, after the latest Flatpak update this feature started working. Very nice :+1:

**Comment by nlogozzo** [comment]
> hello, unfortunately i've tagged the song with picard so it's now working, but this is the report from another song in the same situation
> 
> `Not Found (For usage, please see: https://musicbrainz.org/development/mmd) at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken) at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`1 request, CancellationToken cancellationToken) at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(String entity, String id, String extra, CancellationToken cancellationToken) at MetaBrainz.MusicBrainz.Query.PerformRequestAsync[T](String entity, String id, String extra, CancellationToken cancellationToken) at MetaBrainz.MusicBrainz.Query.LookupRecordingAsync(Guid mbid, Include inc, Nullable`1 type, Nullable`1 status, CancellationToken cancellationToken) at NickvisionTagger.Shared.Models.MusicFile.LoadTagFromMusicBrainzAsync(String acoustIdClientKey, String version, Boolean overwriteTagWithMusicBrainz, Boolean overwriteAlbumArtWithMusicBrainz) in /run/build/org.nickvision.tagger/NickvisionTagger.Shared/Models/MusicFile.cs:line 490`

Well that's just the fact that your file's fingerprint is probably not associated with a song on MusicBrainz

**Comment by nlogozzo** [comment]
Unfortunately, as you can ready about [from the documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/NickvisionApps/Tagger/main/NickvisionTagger.Shared/Docs/html/C/web-services.html), AcoustID and MusicBrainz identification isn't always perfect...there isn't any crashes or specific issues with your file, if the lookup simply can't find a match, it can't find a match. Like I said since it works for most other songs we know it's not a problem with the lookup code.
