### ISSUE TITLE
Custom properties are not available for multiple files

### ISSUE THREAD

**Issue by 239** [NickvisionApps/Tagger#284]
When multiple files are selected **Main**, **Additional** and **File** properties can be edited while **Custom** properties (like `replaygain_album_gain`, `r128_album_gain` or `vorbis-vendor`) are hidden. It can be quite misleading as it looks like they are missing.

**Comment by nlogozzo** [comment]
Well this is by choice. Many files have many and often different custom properties (especially between different file formats) and it would be hard to edit these all together. We could just show the custom properties shared between these files but then the ones that different will disappear which may cause confusion as well. It's not like how we can do `<keep>` for built-in properties such as Title, Artist, Album since we know those properties exists, like I said it's hard to determine a shared consensus of custom properties for multiple files...So we just decided to allow managing of custom properties on a single file basis.

**Comment by fsobolev** [comment]
> So we just decided to allow managing of custom properties on a single file basis.

Maybe a dimmed label under main properties showed when multiple files selected saying something like "Custom properties can only be changed for inidividual files" should be added to prevent confusion?

**Comment by nlogozzo** [comment]
> Maybe a dimmed label under main properties showed when multiple files selected saying something like "Custom properties can only be changed for inidividual files" should be added to prevent confusion?

I mean I hid the whole section to signify this...but I don't see the harm in adding the label to be like the data is still here.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Tagger/releases/tag/2023.9.0-beta1
