### ISSUE TITLE
Tagger opens on super+e

### ISSUE THREAD

**Issue by Nydragon** [NickvisionApps/Tagger#309]
source: flatpak
distro: arch
DE: Gnome 44.4

Since the newest version of tagger (6691bfddedc802c1fa437b8307b941d3480e84f8b4506cefcc3042f03d2bcfc0) , the program opens when I press super+e, overwriting my settings in the gnome keyboard config:

![image](https://github.com/NickvisionApps/Tagger/assets/56591727/b5587eac-aab1-4d6a-a939-28a339f6cc41)

However, this behaviour was not present on the previous version: be3a671fc669ec3fdca73c926d586119c1fcebf075b210f1a7b8f2b055cb3c6a

**Comment by nlogozzo** [comment]
This could be due to the new feature that allows you to open folders with Tagger from the file browser itself:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/609f17d0-27f5-453b-8604-beb90c5385d2)


Could you try going into Files and right clicking a folder, going to "Open" then "Open With" and make sure the default app is set to "Files"?

**Comment by Nydragon** [comment]
Alright, thank you very much @nlogozzo

I did find `inode/directory=org.nickvision.tagger.desktop` in `/var/lib/flatpak/exports/share/applications/mimeinfo.cache`, after deleting that entry the default went back to Nautilus but retaining the possibility of opening a folder with tagger!

I know little about Flatpak, but is there a way to make programs not snatch the default application status when installing them?

**Comment by nlogozzo** [comment]
> I know little about Flatpak, but is there a way to avoid programs snatching the default application status when installing them?

I have no idea, because we didn't do anything to Tagger to try and make it claim default...i'm surprised this happened on your system because when I installed the update Nautilus still remained the default. And I haven't heard of this issue from any other users either...must have been a weird glitch or something.

**Comment by fsobolev** [comment]
> when I installed the update Nautilus still remained the default

I can say the same, Dolphin remained the default for me on KDE. 🤔

**Comment by Nydragon** [comment]
Must have been a bug then, glad it got resolved, thanks!

**Comment by starise** [comment]
> I did find `inode/directory=org.nickvision.tagger.desktop` in `/var/lib/flatpak/exports/share/applications/mimeinfo.cache`, after deleting that entry the default went back to Nautilus but retaining the possibility of opening a folder with tagger!

Thanks man, I was having the same issue with every app. On "open/show folder" use Tagger. Deleting `inode/directory=org.nickvision.tagger.desktop;` from `mimeinfo.cache` solved the issue.

**Comment by Nydragon** [comment]
@starise you might want to execute the following command

> xdg-mime default org.gnome.Nautilus.desktop inode/directory

the cache fix is only temporary until the next boot (my case). From my understanding the reason for this behaviour is that Arch (and other distros) does not ship default mime handlers, so the OS chooses the first software in alphabetical order to open a given file.
