### ISSUE TITLE
On Linux if `File Name` & `Title` contain `<` character, Tagger `File Name` & `Title` preview will show nothing

### ISSUE THREAD

**Issue by kissthermite** [NickvisionApps/Tagger#370]
![1](https://cdn.discordapp.com/attachments/1139923418767175764/1164458556951629824/Screenshot_from_2023-10-19_13-57-49.png?ex=6543498a&is=6530d48a&hm=7ca11c2aa39aedc7e9964974256adde57a74000cf757aabc57eb3b4408e47006&)

![2](https://cdn.discordapp.com/attachments/1139923418767175764/1164458556599316490/Screenshot_from_2023-10-19_13-56-54.png?ex=6543498a&is=6530d48a&hm=9fe463e377bd70f331b5156812f54ef9efa34e430ca95d2d66016dabeda3e87e&)

Not that related but i think it's better to force rename `File Name` if forbidden printable ASCII characters of Windows  (`<` `>` `:` `"` `/` `\` `|` `?` `*`) are present to `_` even on Linux version of Tagger for compatibility reason.

**Comment by nlogozzo** [comment]
The issue with this wasn't the fact of it being an invalid file name character. The problem was gtk/adw widgets by default support a markup language by default when setting text and `<` trigger that markup. So we needed to set `use-markup` to false and that allows the row to display correctly:

![image](https://github.com/NickvisionApps/Tagger/assets/17648453/cd3f5442-10d4-478c-b3c2-5ced1fed99ef)

**Comment by nlogozzo** [comment]
> Not that related but i think it's better to force rename File Name if forbidden printable ASCII characters of Windows (< > : / \ | ? *) are present to _ even on Linux version of Tagger for compatibility reason.

Tagger already checks when changing the file name if the character is valid or not on that system. For Linux, the only invalid character is `/`. So if you try to change the file name to something with `/`, the `/` will be replaced by `_`.  On the Windows version of Tagger, it checks and replaces those invalid characters.

As far as replacing invalid Windows characters on Linux too, I don't think we should do that since most Linux users won't be using Windows and since no other Linux program checks if file names are Windows compatible (besides Parabolic if the option is turned on lol, so maybe we can add that here too?) @fsobolev thoughts?

**Comment by kissthermite** [comment]
> As far as replacing invalid Windows characters on Linux too, I don't think we should do that since most Linux users won't be using Windows and since no other Linux program checks if file names are Windows compatible (besides Parabolic if the option is turned on lol, so maybe we can add that here too?) @fsobolev thoughts?

Understandable, i suppose cross platfrom audio filename incompatibility are outside of Tagger scope.

**Comment by nlogozzo** [comment]
> outside of Tagger scope.

Like I said, Parabolic has this preference:
![image](https://github.com/NickvisionApps/Tagger/assets/17648453/69369e0b-47bd-4366-9f5e-795a3969c1b1)

So we could definitely add that to Tagger too

**Comment by kissthermite** [comment]
> Like I said, Parabolic has this preference: ![image](https://user-images.githubusercontent.com/17648453/276642149-69369e0b-47bd-4366-9f5e-795a3969c1b1.png)
> 
> So we could definitely add that to Tagger too

Hell yeah! that would be awesome. Since Android also have the same filename limitation as Windows.

**Comment by nlogozzo** [comment]
Use https://github.com/NickvisionApps/Tagger/issues/372 to track

**Comment by nlogozzo** [comment]
Please test the latest beta release with this feature: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

*Will be available via `flathub-beta` within the hour*

**Comment by kissthermite** [comment]
> Please test the latest beta release with this fix: https://github.com/NickvisionApps/Tagger/releases/tag/2023.10.0-beta2 and let us know how it goes!

`Limit Filename Characters` does working wonderfully!

![name](https://media.discordapp.net/attachments/1139923418767175764/1165148989516165121/Screenshot_from_2023-10-21_11-45-51.png?ex=6545cc8e&is=6533578e&hm=7913f0d9aa74dd46ca45298a68d6f7dc164f2d92af2256c27a8a5d0fbad43d9e&=&width=692&height=596)

---

Before `Tag to File Name` conversion
![name](https://media.discordapp.net/attachments/1139923418767175764/1165148880812396544/Screenshot_from_2023-10-21_11-44-55.png?ex=6545cc74&is=65335774&hm=41d7095ba2e1187f1ef54e6b049acad02a650a0dbd050f13ced14a7b143a616c&=&width=548&height=596)

---

After `Tag to File Name` conversion with `Limit Filename Characters` turned on and Tag contain forbidden printable ASCII characters of Windows
![name](https://media.discordapp.net/attachments/1139923418767175764/1165148881210843136/Screenshot_from_2023-10-21_11-45-13.png?ex=6545cc74&is=65335774&hm=873eac0e0bc1d7e82cbbb0214d207d67d6b1ff7e72ebe36b632122d30a829291&=&width=548&height=596)
